# -*- coding: utf-8 -*-
"""sales-dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12UV2c-q1NW24zX9GNVDMe6RCaQwABX_4
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/supermarket_sales - Sheet1.csv')
df.head()

# Convert Date column
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.strftime('%B')

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Missing values:", df.isnull().sum().sum())
print("✅ Data is clean and ready!")

plt.figure(figsize=(10, 5))

product_sales = df.groupby('Product line')['Total'].sum().sort_values()

colors = ['#c0392b' if v == product_sales.max()
          else '#f5b7b1' for v in product_sales]

product_sales.plot(kind='barh', color=colors)

plt.title('Total Sales by Product Category',
          fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Total Revenue ($)', fontsize=12)
plt.ylabel('')
plt.tight_layout()
plt.savefig('chart1_product_sales.png', dpi=150, bbox_inches='tight')
plt.show()

print("Best selling category:", product_sales.idxmax())
print("Total Revenue: $", round(product_sales.max(), 2))

plt.figure(figsize=(7, 7))

payment_counts = df['Payment'].value_counts()

colors = ['#c0392b', '#e74c3c', '#f1948a']

plt.pie(payment_counts,
        labels=payment_counts.index,
        autopct='%1.1f%%',
        colors=colors,
        startangle=90,
        wedgeprops={'edgecolor': 'white', 'linewidth': 2})

plt.title('Customer Payment Methods',
          fontsize=16, fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig('chart2_payment_methods.png', dpi=150, bbox_inches='tight')
plt.show()

plt.figure(figsize=(12, 5))

daily_sales = df.groupby('Date')['Total'].sum()

plt.plot(daily_sales.index, daily_sales.values,
         color='#c0392b', linewidth=2)

plt.fill_between(daily_sales.index, daily_sales.values,
                 alpha=0.1, color='#c0392b')

plt.title('Daily Sales Trend',
          fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Total Revenue ($)', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('chart3_daily_trend.png', dpi=150, bbox_inches='tight')
plt.show()

print("=" * 45)
print("      SALES ANALYSIS SUMMARY REPORT")
print("=" * 45)

print(f"\nTotal Revenue:      ${df['Total'].sum():,.2f}")
print(f"Total Transactions: {len(df):,}")
print(f"Average Sale Value: ${df['Total'].mean():.2f}")

print(f"\nTop Product:  {df.groupby('Product line')['Total'].sum().idxmax()}")
print(f"Top Branch:   {df.groupby('Branch')['Total'].sum().idxmax()}")
print(f"Top Payment:  {df['Payment'].value_counts().idxmax()}")

print(f"\nDate Range: {df['Date'].min().date()} "
      f"to {df['Date'].max().date()}")
print("=" * 45)